import './components/login.js'
import './components/menu.js'
import './components/main.js'
import './components/tables/fichajes.js'
import './components/all.js'
import './components/font-loader.js'
import './components/page.js'
import './components/notfound.js'
